### ISSUE TITLE
Database creation issue

### ISSUE THREAD

**Issue by hxsllc** [hafizchin/DomainManager#1]
Regarding https://forum.omeka.org/t/root-url-as-site-1/6204/19

I tried installing today, and ran into database creation issue. It was something about "key too long, 767 max". I didn't take a screenshot but can reproduce.

After a few attempts, I adjusted the SQL table creation query to the following to get it to work. Obviously this is less specified than your original query, but overall points to a more flexible creation statement that doesn't reflect your local environment.

CREATE TABLE `domain_site_mapping` ( 
	`id` INT NOT NULL AUTO_INCREMENT, 
	`site_id` INT NOT NULL, 
	`domain` VARCHAR(253) NOT NULL, 				
	`site_page_id` INT NULL DEFAULT NULL, 
	PRIMARY KEY (`id`), 
	UNIQUE INDEX `DOMAIN_SITE_MAPPING_SITE_ID_UNIQUE` (`site_id` ASC), 
	UNIQUE INDEX `DOMAIN_SITE_MAPPING_DOMAIN_UNIQUE` (`domain` ASC))

**Comment by hafizchin** [comment]
Hi,

Looks like the version of your database (mysql / mariadb) is old.

Kindly refer to this [link](https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes).

This plugin is in its early stage. So any feedback is appreciated.

**Comment by hxsllc** [comment]
Considering the user base of Omeka in general (academia) I would expect a lot of "old" services to be in production still :) At the central/institutional level, maybe not so much. But I am seeing a lot of smaller projects moving to Omeka-S. My vote is always for backwards compatibility to be maintained if possible and simple enough!

**Comment by hafizchin** [comment]
Noted. I have updated the code.

Once again, thanks for the feedback 😄
