### ISSUE TITLE
Doesn't carry over login

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [hafizchin/DomainManager#10]
When I use the domain mapper, it doesn't acknowledge whether or not I'm logged into the Omeka-S instance while on the mapped site. Therefore private items do not show up if I'm logged in.

**Comment by hafizchin** [comment]
Hi @fitnycdigitalinitiatives,

Here's what I see. Do you mind sharing some screenshots?

**Item**

![image](https://user-images.githubusercontent.com/6478018/132892844-606749bc-d1ff-4a1d-9dc2-73bab22a0935.png)

**Authenticated User**
![image](https://user-images.githubusercontent.com/6478018/132893268-3ba97d76-c4fa-4b91-b108-4b4bf9fef6f1.png)

**Incognito Mode**
![image](https://user-images.githubusercontent.com/6478018/132893212-8b215922-f32c-4f91-b3c5-d6f50baebd48.png)

**Comment by fitnycdigitalinitiatives** [comment]
Thanks for the quick response.

When I visit the site itself, I don't get the the login bar at the top of the screen:

![image](https://user-images.githubusercontent.com/12830594/132895125-cfc6719d-f355-4ed3-927d-f1c0e0ce97ba.png)

One thing to note is that I'm using this module on Omeka S 3.10 and also using it on localhost, so this site uses institutionalrepository.localhost—haven't tried it in production yet

**Comment by hafizchin** [comment]
- Which webserver are you using? 
- Can you share a screenshot of the DomainManager UI?

**Comment by fitnycdigitalinitiatives** [comment]
![image](https://user-images.githubusercontent.com/12830594/132896207-4e2beb1e-b672-4a9e-9344-462ca5352ec9.png)
and using apache
![image](https://user-images.githubusercontent.com/12830594/132896518-09a520a0-e763-4871-8a8e-522f8bb03906.png)

**Comment by hafizchin** [comment]
How do you access the item? it should be **http://institutionalrepository.localhost/item/[ITEM_ID]**

also you have to assign that item to that site

**Comment by fitnycdigitalinitiatives** [comment]
Yeah, I've been doing that it's not working. I think I'll try to set this up on my production site and see what happens. Maybe the issue is because it's running locally out of a docker container??

Have you had luck doing this on localhost?

**Comment by hafizchin** [comment]
Im running it on a dev server (as this module is not yet production ready)

**Comment by fitnycdigitalinitiatives** [comment]
Ok, I tried it also on my production site to no avail.

One thing I noticed is that in inspecting the session cookie in chrome, it says that the one that has my login info is blocked from the mapped site because it doesn't match the domain and or isn't a subdomain, so therefore it's not recognizing that I'm logged in.

**Comment by hafizchin** [comment]
I think it has something to do with your apache config

**Comment by fitnycdigitalinitiatives** [comment]
Ok, I was finally able to get this to work. What I needed to do was to manually set the php session cookie domain in the .htaccess file (there are other ways to do so here: https://stackoverflow.com/questions/644920/allow-php-sessions-to-carry-over-to-subdomains so presumably this could be added to the module itself or something). Once this is set, then the authentication cookie that is written at the server domain can also be used for the subdomain. So, I set the cookie domain as for instance fitnyc.local and then the site is mapped to institutionalrepository.fitnyc.local and it works. The private items show up and admin bar is at the top of the page.
What is confusing for me is why it was necessary for me to set this, but it's not necessary on your end. Is your server setting this php setting as default and mine isn't? Based on what I could tell from reading php documentation, if this isn't set then the browser will reject using the cookie at a subdomain.

Thanks for your help with this!

**Comment by hafizchin** [comment]
Looking at php.ini, that config set as is (blank).

But looking at my vhost file (I suspect this is the code that allows it)

` 
#Implement CORS

SetEnvIf Origin "^(.*\.MYDOMAIN\.COM)$" ORIGIN_SUB_DOMAIN=$1

Header set Access-Control-Allow-Origin "%{ORIGIN_SUB_DOMAIN}e" env=ORIGIN_SUB_DOMAIN

Header merge Vary "Origin" env=ORIGIN_SUB_DOMAIN

Header always setifempty X-Frame-Options "SAMEORIGIN"
`

**Comment by fitnycdigitalinitiatives** [comment]
Yeah, doesn't look any of my apache config has that kinda of stuff, so maybe that explains it. I can just set it this way for our purposes. Thanks so much for your assistance—really appreciate it!
