### ISSUE TITLE
Configuring virtual host

### ISSUE THREAD

**Issue by marlara** [hafizchin/DomainManager#11]
Hi! I have installed Omeka S in a server and now I want to migrate the address into a proper domain. I am trying to use the module and in Apache I set the `000-defaulf.conf file` and the `default-ssl.conf` like this:

> <VirtualHost *:80>
> 
>         ServerAdmin webmaster@localhost
>         DocumentRoot /var/www/html
>         ServerName my-site.domain.it
>         ServerAlias www.my-site.domain.it

In the module I put the my-site.domain.it address, but it then gives me this error:

> Oops!
> It looks like srv-omeka-01.domain.it is not mapped to a site.

Should I not use the default.conf file or is it another problem I am experiencing? Thank you

**Comment by hafizchin** [comment]
Please enable error logging so we can see the actual error message

**Comment by marlara** [comment]
This is the error log:

> error.log                                                                                                
> [Thu Oct 14 00:00:01.768371 2021] [mpm_prefork:notice] [pid 1809] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
> [Thu Oct 14 00:00:01.768394 2021] [core:notice] [pid 1809] AH00094: Command line: '/usr/sbin/apache2'
> [Thu Oct 14 03:53:01.256275 2021] [core:error] [pid 96505] [client 45.146.164.110:39374] AH00126: Invalid URI in request POST /cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1
> [Thu Oct 14 11:12:40.266237 2021] [mpm_prefork:notice] [pid 1809] AH00169: caught SIGTERM, shutting down
> [Thu Oct 14 11:12:40.362046 2021] [mpm_prefork:notice] [pid 211373] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
> [Thu Oct 14 11:12:40.362087 2021] [core:notice] [pid 211373] AH00094: Command line: '/usr/sbin/apache2'
> 

And this is the last part of the access log:

> 
> 111.7.100.23 - - [14/Oct/2021:12:59:55 +0200] "GET / HTTP/1.1" 200 3440 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
> 111.7.100.23 - - [14/Oct/2021:13:01:33 +0200] "GET / HTTP/1.1" 200 3477 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
> 111.7.100.23 - - [14/Oct/2021:13:01:34 +0200] "GET /icons/ubuntu-logo.png HTTP/1.1" 200 3623 "http://mostra1972.unipr.it/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko>
> 111.7.100.20 - - [14/Oct/2021:13:01:37 +0200] "GET / HTTP/1.1" 200 3477 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
> 36.99.136.140 - - [14/Oct/2021:13:02:39 +0200] "GET /manual HTTP/1.1" 404 461 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
> 36.99.136.142 - - [14/Oct/2021:13:04:14 +0200] "GET /manual HTTP/1.1" 404 498 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
> 36.99.136.142 - - [14/Oct/2021:13:04:18 +0200] "GET /manual HTTP/1.1" 404 497 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
> 36.99.136.137 - - [14/Oct/2021:13:10:48 +0200] "GET / HTTP/1.1" 200 3440 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
> 36.99.136.137 - - [14/Oct/2021:13:12:19 +0200] "GET / HTTP/1.1" 200 3477 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
> 36.99.136.137 - - [14/Oct/2021:13:12:24 +0200] "GET /icons/ubuntu-logo.png HTTP/1.1" 200 3623 "http://www.mostra1972.unipr.it/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like >
> 36.99.136.137 - - [14/Oct/2021:13:12:28 +0200] "GET / HTTP/1.1" 200 3476 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
> 36.99.136.138 - - [14/Oct/2021:13:13:22 +0200] "GET /manual HTTP/1.1" 404 465 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
> 36.99.136.140 - - [14/Oct/2021:13:14:51 +0200] "GET /manual HTTP/1.1" 404 502 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36"
> 209.141.56.212 - - [14/Oct/2021:13:22:30 +0200] "GET /config/getuser?index=0 HTTP/1.1" 404 455 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
> 186.33.100.72 - - [14/Oct/2021:13:29:59 +0200] "GET / HTTP/1.1" 200 11173 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
> 104.47.2.254 - - [14/Oct/2021:13:36:47 +0200] "HEAD / HTTP/1.1" 200 274 "-" "-"
> 40.94.104.35 - - [14/Oct/2021:13:36:59 +0200] "GET / HTTP/1.1" 200 3477 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.136 Safari/537.36"
> 40.94.104.76 - - [14/Oct/2021:13:37:00 +0200] "GET /icons/ubuntu-logo.png HTTP/1.1" 200 3624 "http://www.mostra1972.unipr.it/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like G>
> 40.94.104.76 - - [14/Oct/2021:13:37:04 +0200] "GET /favicon.ico HTTP/1.1" 404 501 "http://www.mostra1972.unipr.it/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrom>
> 160.78.142.74 - - [14/Oct/2021:13:42:09 +0200] "POST /omeka-s/admin/module/activate?id=DomainManager HTTP/1.1" 403 9845 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu; Linu>
> 160.78.142.74 - - [14/Oct/2021:13:42:12 +0200] "POST /omeka-s/admin/module/activate?id=DomainManager HTTP/1.1" 403 9844 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu; Linu>
> 160.78.142.74 - - [14/Oct/2021:13:42:12 +0200] "GET /omeka-s/application/asset/vendor/tablesaw/tablesaw.stackonly.jquery.js?v=3.0.1 HTTP/1.1" 200 5456 "http://srv-omeka-01.unipr.it/omeka-s/admin/module/a>
> 160.78.142.74 - - [14/Oct/2021:13:42:12 +0200] "GET /omeka-s/application/asset/vendor/chosen-js/chosen.jquery.js?v=3.0.1 HTTP/1.1" 200 8714 "http://srv-omeka-01.unipr.it/omeka-s/admin/module/activate?id=>
> 160.78.142.74 - - [14/Oct/2021:13:42:12 +0200] "GET /omeka-s/application/asset/js/global.js?v=3.0.1 HTTP/1.1" 200 931 "http://srv-omeka-01.unipr.it/omeka-s/admin/module/activate?id=DomainManager" "Mozill>
> 160.78.142.74 - - [14/Oct/2021:13:42:12 +0200] "GET /omeka-s/application/asset/js/admin.js?v=3.0.1 HTTP/1.1" 200 5346 "http://srv-omeka-01.unipr.it/omeka-s/admin/module/activate?id=DomainManager" "Mozill>
> 160.78.142.74 - - [14/Oct/2021:13:42:12 +0200] "GET /omeka-s/application/asset/js/chosen-options.js?v=3.0.1 HTTP/1.1" 200 536 "http://srv-omeka-01.unipr.it/omeka-s/admin/module/activate?id=DomainManager">
> 160.78.142.74 - - [14/Oct/2021:13:42:25 +0200] "GET /omeka-s/admin/module HTTP/1.1" 200 5365 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20>
> 160.78.142.74 - - [14/Oct/2021:13:42:25 +0200] "GET /omeka-s/application/asset/vendor/semver/semver.min.js?v=3.0.1 HTTP/1.1" 200 4142 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11>
> 160.78.142.74 - - [14/Oct/2021:13:42:30 +0200] "GET /omeka-s/admin/module HTTP/1.1" 200 5364 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20>
> 160.78.142.74 - - [14/Oct/2021:13:42:30 +0200] "GET /omeka-s/application/asset/vendor/tablesaw/tablesaw.stackonly.jquery.js?v=3.0.1 HTTP/1.1" 200 5455 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" >
> 160.78.142.74 - - [14/Oct/2021:13:42:30 +0200] "GET /omeka-s/application/asset/js/global.js?v=3.0.1 HTTP/1.1" 200 932 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu; Linux >
> 160.78.142.74 - - [14/Oct/2021:13:42:30 +0200] "GET /omeka-s/application/asset/js/admin.js?v=3.0.1 HTTP/1.1" 200 5346 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu; Linux >
> 160.78.142.74 - - [14/Oct/2021:13:42:30 +0200] "GET /omeka-s/application/asset/js/chosen-options.js?v=3.0.1 HTTP/1.1" 200 536 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu>
> 160.78.142.74 - - [14/Oct/2021:13:42:30 +0200] "GET /omeka-s/application/asset/vendor/semver/semver.min.js?v=3.0.1 HTTP/1.1" 200 4143 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11>
> 160.78.142.74 - - [14/Oct/2021:13:42:30 +0200] "GET /omeka-s/application/asset/vendor/chosen-js/chosen.jquery.js?v=3.0.1 HTTP/1.1" 200 8715 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.>
> 160.78.142.74 - - [14/Oct/2021:13:42:31 +0200] "POST /omeka-s/admin/module/activate?id=DomainManager HTTP/1.1" 302 348 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu; Linux>
> 160.78.142.74 - - [14/Oct/2021:13:42:31 +0200] "GET /omeka-s/admin/module HTTP/1.1" 200 5409 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20>
> 160.78.142.74 - - [14/Oct/2021:13:42:33 +0200] "GET /omeka-s/admin/module/configure?id=DomainManager HTTP/1.1" 200 3188 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu; Linu>
> 160.78.142.74 - - [14/Oct/2021:13:42:38 +0200] "GET /omeka-s/admin/site HTTP/1.1" 200 3236 "http://srv-omeka-01.unipr.it/omeka-s/admin/module/configure?id=DomainManager" "Mozilla/5.0 (X11; Ubuntu; Linux >
> 160.78.142.74 - - [14/Oct/2021:13:42:40 +0200] "GET /omeka-s/s/1972_mostra HTTP/1.1" 200 1086 "http://srv-omeka-01.unipr.it/omeka-s/admin/site" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/201>
> ::1 - - [14/Oct/2021:13:42:46 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
> 160.78.142.74 - - [14/Oct/2021:13:42:56 +0200] "GET /omeka-s/admin/module HTTP/1.1" 200 5369 "http://srv-omeka-01.unipr.it/omeka-s/admin/site" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/2010>
> 160.78.142.74 - - [14/Oct/2021:13:43:00 +0200] "POST /omeka-s/admin/module/deactivate?id=DomainManager HTTP/1.1" 302 348 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu; Lin>
> 160.78.142.74 - - [14/Oct/2021:13:43:00 +0200] "GET /omeka-s/admin/module HTTP/1.1" 200 5409 "http://srv-omeka-01.unipr.it/omeka-s/admin/module" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20>
> 46.238.231.35 - - [14/Oct/2021:13:54:57 +0200] "GET / HTTP/1.1" 200 11173 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
> 192.144.212.18 - - [14/Oct/2021:14:13:08 +0200] "GET / HTTP/1.1" 200 11229 "-" "-"
> 209.141.62.185 - - [14/Oct/2021:14:27:19 +0200] "GET /config/getuser?index=0 HTTP/1.1" 404 455 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
> 65.49.20.68 - - [14/Oct/2021:14:39:00 +0200] "GET / HTTP/1.1" 200 11173 "-" "-"
>

**Comment by hafizchin** [comment]
Is your server configured to display errors? Im using apache fpm and I have set this config:

`php_admin_flag[display_errors] = on`

Once you set that to on, can you access the page and share the output here

**Comment by marlara** [comment]
I'm sorry for asking, but do I have to set this in the .htaccess file?

**Comment by hafizchin** [comment]
Are you using php-fpm? if yes, that setting is usually set here `/etc/php/7.2/fpm/pool.d/www.conf` (your php version might be different).

You can also try [this](https://stackify.com/display-php-errors/).

**Comment by marlara** [comment]
Hi, sorry for the late reply. I use php cli. I already set On all the errors, both from .htaccess than from php.ini. When I run a phpinfo() I have all set properly:

```
display_errors => STDOUT => STDOUT
display_startup_errors => On => On
error_log => /var/www/html/omeka-s/logs/php_errors.log => /var/www/html/omeka-s/logs/php_errors.log
error_reporting => 32767 => 32767
```
I restarted apache already. But when I try to reach the site I still don't have errors shown, nor any logs in the logging file... Maybe it's Omeka that overwrite all the configurations?

![Schermata da 2021-10-18 09-34-27](https://user-images.githubusercontent.com/12834687/137687944-fbef0e01-7f63-4c4f-be56-5d0db55ce6c2.png)

**Comment by hafizchin** [comment]
Hi,

Can you show me the apache vhost config of your omeka site and a screenshot of the module configuration page.

**Comment by marlara** [comment]
Hi, 
here it is. Thank you very much
![Schermata da 2021-10-18 18-58-52](https://user-images.githubusercontent.com/12834687/137775904-0ad8bf37-8b97-45b1-8753-1cbd5bcefa44.png)
![Schermata da 2021-10-18 19-01-34](https://user-images.githubusercontent.com/12834687/137775907-b41af113-febc-4764-957d-08ef3e845e71.png)

**Comment by hafizchin** [comment]
Looking at the error message (attached image), you are accessing `svr-omeka-01.unipr.it`. Which is not configured

What do you see when you access these URLs:

- [mostra1972.unipr.it](mostra1972.unipr.it)
- [www.mostra1972.unipr.it](www.mostra1972.unipr.it)

**Comment by marlara** [comment]
I see the Apache general page

Il lun 18 ott 2021, 22:31 Mo Hechanova ***@***.***> ha
scritto:

**Comment by hafizchin** [comment]
can you confirm that your vhost is up to date and apache is restarted after the update.

**Comment by hafizchin** [comment]
![image](https://user-images.githubusercontent.com/6478018/137802916-fb38cd33-f214-4dfe-bdb0-d100858624ad.png)

Looks like the file was not updated because of permission issue

**Comment by marlara** [comment]
Yes I think so

Il lun 18 ott 2021, 22:34 Mo Hechanova ***@***.***> ha
scritto:

**Comment by marlara** [comment]
Yes but that was just to take the picture, it was already set that way and
I restarted apache this afternoon. Sorry it wasn't clear

Il lun 18 ott 2021, 22:35 Mo Hechanova ***@***.***> ha
scritto:

**Comment by hafizchin** [comment]
The module works.

![image](https://user-images.githubusercontent.com/6478018/137803553-84d17f71-ff53-42e2-8775-b837d01889ff.png)

Please note that you can only map 1 domain name per site (the module does not support multiple domain names)

Like in 

![image](https://user-images.githubusercontent.com/6478018/137803692-9b4fd72c-55b3-420b-b3a5-bcfc20e53dab.png)

`1972. Moda, design, storia` will be mapped to [mostra1972.unipr.it](http://mostra1972.unipr.it/)

**Comment by marlara** [comment]
Oh, wow, thanks! And how can I manage to do that from the admin panel of omeka it will go there? Because now I get the error above

**Comment by hafizchin** [comment]
As I've mentioned, this module can only map one site per domain.

And as per your screenshot, you only have a single site in your omeka-s instance.

You can configure the plugin by heading to:

Omeka S Admin -> Module -> DomainManager -> Configure

Refer to your screenshot

**Comment by marlara** [comment]
Sorry to bother you again, just one last question, because I don't think I'm understanding it right: what do I have to write in `ServerName` inside the `000-default.conf` file? Right now I put where the site is: `srv-omeka-01.unipr.it/s/1972_mostra`: so the server in which there is the omeka installation, then the `/s/` and then the site slug. 
The configuration of the module seems right, I must do wrong the `ServerName` at this point.

**Comment by hafizchin** [comment]
omeka-s was designed to host multiple sites in a single instance.
The purpose of this plugin is to allow each sites to have their own domain name. Without the plugin, omeka-s will append `/s/SITE_NAME` to the URL.

So if your omeka-s has multiple sites, you would typically put the main site in `ServerName` while the rest of the sites will be a `ServerAlias` entry

In your case, the `ServerName` entry will be the one you would map to your site. Both `ServerName` and `ServerAlias` points to the same omeka-s instance. The plugin will resolve the URL to the assigned site.

**Comment by marlara** [comment]
Yeah, ok. The module it's actually working, the only thing is that from that page

![Schermata da 2021-10-20 10-40-28](https://user-images.githubusercontent.com/12834687/138059121-1dcf4ba0-2aa0-42ed-ae7a-536948c7b353.png)

 it's not redirecting to the right domain, even if it is configured properly. I don't know at this point, you can close the issue, I cannot figure it out why it does like that...



![Schermata da 2021-10-20 10-42-11](https://user-images.githubusercontent.com/12834687/138059536-b8c61d74-9f73-4f3f-b2b0-144d9f0fd8d9.png)
![Schermata da 2021-10-20 10-41-49](https://user-images.githubusercontent.com/12834687/138059539-b10435fc-bb90-4974-97e9-6ee35cc98e69.png)

**Comment by hafizchin** [comment]
Im not sure what you mean by it's not redirecting to the right domain.

I can access the site `http://mostra1972.unipr.it/`

**Comment by marlara** [comment]
Just that if I click on the arrow that should lead me to the website from
the admin page (first screenshot) it gives me the error message. Same thing
if I want to see a specific page that I'm editing.

Il giorno mer 20 ott 2021 alle ore 14:22 Mo Hechanova <
***@***.***> ha scritto:

**Comment by hafizchin** [comment]
Hi,

Oh I see what you mean, can you pull the latest version. Let me know if it works!

**Comment by marlara** [comment]
YES IT'S WORKING!
Thank you so much, I was going crazy :)

**Comment by marlara** [comment]
Sorry just another little thing: when I click on a specific page from here
![Schermata da 2021-10-21 09-35-32](https://user-images.githubusercontent.com/12834687/138232458-439c7197-25c2-4297-b17d-a1a6371ede8d.png)

it doubles the base url

![Schermata da 2021-10-21 09-35-27](https://user-images.githubusercontent.com/12834687/138232490-f404c8c8-a34d-492e-9644-52609e6bf4e1.png)

**Comment by hafizchin** [comment]
Please pull the latest version
