### ISSUE TITLE
Incompatibility with Collecting module

### ISSUE THREAD

**Issue by pprw** [hafizchin/DomainManager#3]
There is a bug when using this module with the [Collecting module](https://github.com/omeka-s-modules/Collecting).

After sending a form, Collecting module is launching the page `https://.../s/.../collecting/1/success` which is not found when OmekaSDomainManager is active.

Since it is OmekaSDomainManager which change the default behavior of Omeka S, the correction should probably be done in this module.

See https://github.com/omeka-s-modules/Collecting/issues/46#issuecomment-528931535

**Comment by hafizchin** [comment]
Hi,

Thank for you for reporting this issue.

I have deployed a fix.  Let me know if the issue is resolved.

Regards,

Mo

**Comment by pprw** [comment]
I can confirm it is working now.

Thanks!
