### ISSUE TITLE
Incompatibility with Solr/Search modules

### ISSUE THREAD

**Issue by pprw** [hafizchin/DomainManager#6]
urls generates by [Search](https://github.com/Daniel-KM/omeka-s-module-Search)/[Solr](https://github.com/Daniel-KM/Omeka-S-module-Solr) modules such as:

https://installation/s/site/solr
https://installation/s/site/find

are redirect when using this module to

https://installation/solr
https://installation/find

which display an error.

**Comment by hafizchin** [comment]
Hi,

Sorry for the late reply. Can you try using the latest version of DomainManager and let me know if it works.

**Comment by pprw** [comment]
I just tested. It doesn't work with the current master version.

**Comment by hafizchin** [comment]
I have updated the code. Kindly test and let me know if it works.
