### ISSUE TITLE
Empty breadcumbs

### ISSUE THREAD

**Issue by JorisLambrechts** [hafizchin/DomainManager#7]
The zend function breadcrumbs() no longer returns anything when using this module.

I think because it can't find an active page (it relies on the navigation container (publicNav()).

I figured out that in Omeka-s, whether a page is active or not is determined by the route match object.

With the module installed and active the route match object looks like this:
`object(Zend\Router\Http\RouteMatch)#921 (3) { ["length":protected]=> int(17) ["params":protected]=> array(6) { ["__NAMESPACE__"]=> string(21) "Omeka\Controller\Site" ["__SITE__"]=> bool(true) ["controller"]=> string(4) "Page" ["action"]=> string(4) "show" ["site-slug"]=> string(5) "start" ["page-slug"]=> string(11) "registreren" } ["matchedRouteName":protected]=> string(17) "start-routes/page" } `

I did some testing and if I change $route-key from 'site slug-routes' to just 'site' the breadcrumbs start working again but this breaks the redirect from /s/slug/page/test to /page/test among other things.

The route match object in this last case:
`object(Zend\Router\Http\RouteMatch)#184 (3) { ["length":protected]=> int(17) ["params":protected]=> array(6) { ["__NAMESPACE__"]=> string(21) "Omeka\Controller\Site" ["__SITE__"]=> bool(true) ["controller"]=> string(4) "Page" ["action"]=> string(4) "show" ["site-slug"]=> string(5) "start" ["page-slug"]=> string(11) "registreren" } ["matchedRouteName":protected]=> string(9) "site/page" } `

Edit: The problem is propably that the public navigation generated in the view does not take this module into account.

**Comment by hafizchin** [comment]
Hi,

Thanks for reporting the issue. I have updated the code. Let me know if your issue has been resolved.

**Comment by JorisLambrechts** [comment]
That fixed it, thanks!
