### ISSUE TITLE
One site at time, my two sites doesn't work together

### ISSUE THREAD

**Issue by HHeimlich** [hafizchin/DomainManager#8]
Hello, hoping you are doing well, I write searching for some light.

I have two sites and two domains. The old one is working good but the new one doesn't and vice versa.

My configuration:

Debian 9
Omeka-S 2.1.2
Domain Manager 1.2 activated
Apache 2.4.25
My first (long last working) site: https://biblioteca.represion.org
My second (brand new) site: https://biblioteca.resistencia.org

**Scenario 1**. Currently virtual host for my _first site_ is enabled and configured like this:

ServerName: www.biblioteca.represion.org
ServerAlias: biblioteca.represion.org
DocumentRoot: /var/www/html

Virtual host for _my second site_ is **disabled** but it is configured like this:

ServerName: www.biblioteca.resistencia.org
ServerAlias: biblioteca.resistencia.org
DocumentRoot: /var/www/html

DomainManager is activated and configured like this:

Site | Domain
Biblioteca Represión | biblioteca.represion.org
Biblioteca Resistencia | biblioteca.resistencia.org

**Result:** _My second site_ (Archivos de la resistencia) works fine when I type biblioteca.resistencia.org on my browser but when I type biblioteca.represion.org Omeka-S shows a Not found page.

**Scenario 2**. I enable the virtual host for _my second site_ 

**Result:** Omeka-S still showing Not Found page for my first site and Apache2 shows its Not found page for my second site.

**Scenario 3**.  I desactivate DomainManager module (and virtual host for second site remains enabled).

**Result:** _My first site_ works fine but my second site doesn’t work and Apache 2 displays its Not found page.

**Scenario 4**. I disable virtual host for _my second site_  (and DomainManager remains desactivated).

**Result:** Both domains shows the contents of my first site.

For any help, thanks a lot in advance!

**Comment by hafizchin** [comment]
Hi!

Can you send me a screenshot of the domain manager settings page? Also, there any other errors aside from the 404?

**Comment by HHeimlich** [comment]
Hi hafizchin!

Thanks a lot for your help. I didn't see other errors. The images I attach here are for the scenario 1, the second site works fine.

![ONF](https://user-images.githubusercontent.com/4049585/101185923-5ff05d80-364a-11eb-88fd-3b51602ac427.png)
![domainManager](https://user-images.githubusercontent.com/4049585/101185927-61218a80-364a-11eb-8ad0-370b45cfb8fc.png)

Good friday.

**Comment by hafizchin** [comment]
Just to sure, both site has atleast 1 active page?

**Comment by HHeimlich** [comment]
Hi.

Yes, as long as I understand, they have it:

![pagsRss](https://user-images.githubusercontent.com/4049585/101188522-bca14780-364d-11eb-98d3-8a37ccec7904.png)
![pagsR](https://user-images.githubusercontent.com/4049585/101188525-bd39de00-364d-11eb-8668-b97339c366ca.png)

**Comment by hafizchin** [comment]
Hi,

I think I found the issue with your configuration. In order for the plugin to work properly, your omeka-s installation should have a single virtual host.

Please use this as an example:

```
<VirtualHost *:443>
     ServerName biblioteca.represion.org
     ServerAlias biblioteca.resistencia.org
     DocumentRoot /var/www/html
</VirtualHost>
```

As you can see from the example, your ServerName is the url of your **primary site** and any additional sites will be a **ServerAlias** entry.

Let me know if this resolves your issue.

**Comment by HHeimlich** [comment]
I will try now and of course I will let you know. I must do it.

Thanks a lot.

**Comment by HHeimlich** [comment]
Hi!

I confirm that now the both sites are working fine at the same time.

Thanks again for the kindly help.
